# Generated by Django 5.1.1 on 2024-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ip', models.CharField(max_length=100, null=True, verbose_name='آیپی')),
                ('Email', models.CharField(max_length=200, verbose_name='Email')),
                ('Password', models.CharField(max_length=255, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='SingIn',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ip', models.CharField(max_length=100, null=True, verbose_name='آیپی')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('Email', models.CharField(max_length=200, verbose_name='Email')),
                ('Password', models.CharField(max_length=255, verbose_name='Password')),
            ],
        ),
    ]
