# Generated by Django 5.1.1 on 2024-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_contactus_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='id',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
