# Generated by Django 5.1.1 on 2024-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_remove_contactus_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
