# Generated by Django 5.1.1 on 2024-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_contactus_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
